// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp728aQ1FviNBrS2fAfMxZgzwgUp3F39I',
    appId: '1:25154560706:web:c8afbf6be5a023c7e7915b',
    messagingSenderId: '25154560706',
    projectId: 'tradehup-3bb85',
    authDomain: 'tradehup-3bb85.firebaseapp.com',
    storageBucket: 'tradehup-3bb85.firebasestorage.app',
    measurementId: 'G-4P892MFW0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBzY2gb45DOVYd59MuVrEuujDCXK6E1BE',
    appId: '1:25154560706:android:f41287085314e653e7915b',
    messagingSenderId: '25154560706',
    projectId: 'tradehup-3bb85',
    storageBucket: 'tradehup-3bb85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG_eqZktAjF8-HzeghjRCoX3xAL51QeRA',
    appId: '1:25154560706:ios:d2ecebaa3c59dbb0e7915b',
    messagingSenderId: '25154560706',
    projectId: 'tradehup-3bb85',
    storageBucket: 'tradehup-3bb85.firebasestorage.app',
    iosBundleId: 'com.example.tradehub',
  );
}
