// Mocks generated by Mockito 5.4.4 from annotations
// in tradehub/test/features/home/data/data_source/get_all_category_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tradehub/features/main_layout/home/data/api/home_api_client.dart'
    as _i4;
import 'package:tradehub/features/main_layout/home/data/models/responses/get_all_category_response.dart'
    as _i6;
import 'package:tradehub/features/main_layout/home/data/models/responses/get_companies.dart'
    as _i2;
import 'package:tradehub/features/main_layout/home/data/models/responses/get_random_products_response.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetCompanies_0 extends _i1.SmartFake implements _i2.GetCompanies {
  _FakeGetCompanies_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetRandomProductsResponse_1 extends _i1.SmartFake
    implements _i3.GetRandomProductsResponse {
  _FakeGetRandomProductsResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeApiClient extends _i1.Mock implements _i4.HomeApiClient {
  MockHomeApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.GetAllCategoryResponse>> getAllCategory() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCategory,
          [],
        ),
        returnValue: _i5.Future<List<_i6.GetAllCategoryResponse>>.value(
            <_i6.GetAllCategoryResponse>[]),
      ) as _i5.Future<List<_i6.GetAllCategoryResponse>>);

  @override
  _i5.Future<_i2.GetCompanies> getCompanies() => (super.noSuchMethod(
        Invocation.method(
          #getCompanies,
          [],
        ),
        returnValue: _i5.Future<_i2.GetCompanies>.value(_FakeGetCompanies_0(
          this,
          Invocation.method(
            #getCompanies,
            [],
          ),
        )),
      ) as _i5.Future<_i2.GetCompanies>);

  @override
  _i5.Future<_i3.GetRandomProductsResponse> getRandomProducts({
    int? pageIndex,
    int? pageSize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomProducts,
          [],
          {
            #pageIndex: pageIndex,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i5.Future<_i3.GetRandomProductsResponse>.value(
            _FakeGetRandomProductsResponse_1(
          this,
          Invocation.method(
            #getRandomProducts,
            [],
            {
              #pageIndex: pageIndex,
              #pageSize: pageSize,
            },
          ),
        )),
      ) as _i5.Future<_i3.GetRandomProductsResponse>);
}
